#include <stdio.h>

int main(int argc, char* argv[]){
	/*
	 * Code generated by the FLTC - Float Code Compiler;
	 * More information at https://github.com/texugo-lab/fltc
	 */
	long int ident = 9;
	return ident;

	return 0;
}