#include "essentials.h"
#include "lexer.c"

#pragma once

#define MAX_VARIABLES 1024

strng nmbrVariables[MAX_VARIABLES] = {};

void variableAppend(strng identifier) {
	for (int i = 0; i < MAX_VARIABLES; ++i) {
		if (!nmbrVariables[i]) {
			nmbrVariables[i] = strdup(identifier);
			break;
		}
	}
}

bool variableExists(strng identifier) {
	for (int i = 0; i < MAX_VARIABLES; ++i) {
		if (!nmbrVariables[i]) continue;
		if (strcmp(identifier, nmbrVariables[i]) == 0) {
			return true;
		}
	}
	return false;
}

bool nmbrCheck(Token token) {
	return token.type == NUMBER ||
		   token.type == IDENTIFIER;
}

strng parse(Tokens tokenTable) {
	Token* tokens = tokenTable.tokens;
	strng cGeneratedCode =
		"\t/* Code generated by the FLTC - Float Code Compiler */\n"
		"\t/* More information at https://github.com/texugo-lab/fltc */\n";

	for (int i = 0; i <= MAX_TOKENS; ++i) {
		if (!tokens[i].token || !tokens[i].type) break;

		if (tokens[i].type == NEWLINE) continue;
		if (tokens[i].type == KEYWORD && strcmp(tokens[i].token, "return") == 0) {
			if (nmbrCheck(tokens[i + 1]) && tokens[i + 2].type == NEWLINE) {
				if (tokens[i + 1].type == NUMBER) {
					cGeneratedCode = textFormat("%s\treturn %s;\n", cGeneratedCode, tokens[i + 1].token);
				} else if (tokens[i + 2].type == IDENTIFIER) {
				}
				i += 3;
			}
			continue;
		}
		if (tokens[i].type == VARIABLE && tokens[i + 1].type == IDENTIFIER && tokens[i + 2].type == ASSIGNMENT && tokens[i + 4].type == NEWLINE) {
			if (strcmp(tokens[i].token, variables[NUMBER_VAR]) == 0 && nmbrCheck(tokens[i + 3])) {
				cGeneratedCode = textFormat("%s\tnmbr %s = %s;\n", cGeneratedCode, tokens[i + 1].token, tokens[i + 3].token);
				variableAppend(tokens[i + 1].token);
				i += 5;
			}
			continue;
		}
		printf("Invalid Expression");
		exit(1);
	}
	return cGeneratedCode;
}
