#include "essentials.h"
#include "lexer.c"

#pragma once

strng parse(Token* tokens) {
	strng cGeneratedCode =
		"\t/* Code generated by the FLoaT Code compiler */\n"
		"\t/* More information at https://github.com/texugo-lab/fltc */\n";

	for (int i = 0; i <= MAX_TOKENS; ++i) {
		if (!tokens[i].token || !tokens[i].type) break;

		printf("(%s)->%c\n", (strcmp(tokens[i].token, "\n") == 0) ? "\\n" : tokens[i].token, tokens[i].type);

		if (tokens[i].type == NEWLINE) continue;
		if (tokens[i].type == KEYWORD && strcmp(tokens[i].token, "return") == 0) {
			if (tokens[i + 1].type == NUMBER && tokens[i + 2].type == NEWLINE) {
				cGeneratedCode = textFormat("%s\treturn %s;\n", cGeneratedCode, tokens[i + 1].token);
				i += 3;
			}
			continue;
		}
		if (tokens[i].type == VARIABLE && tokens[i + 1].type == IDENTIFIER && tokens[i + 2].type == ASSIGNMENT && tokens[i + 4].type == NEWLINE) {
			if (strcmp(tokens[i].token, variables[NUMBER_VAR]) == 0 && tokens[i + 3].type == NUMBER) {
				cGeneratedCode = textFormat("%s\t// nmbr %s = nmbrVar(%s, 0);\n", cGeneratedCode, tokens[i + 1].token, tokens[i + 3].token);
				i += 4;
			}
			continue;
		}
		printf("Invalid Expression");
		exit(1);
	}
	return cGeneratedCode;
}
