#include "essentials.h"
#include "lexer.c"

#pragma once

#define MAX_VARIABLES 1024
#define VARIABLE_COUNT sizeof(variables) / sizeof(variables[0])

#define KEYWORD_COUNT sizeof(keywords) / sizeof(keywords[0])

strng variableTables[VARIABLE_COUNT][MAX_VARIABLES] = {};

void variableAppend(strng identifier, int type);
int variableExists(strng identifier);
int getVariableKeyword(strng keyword);
int getKeyword(strng keyword);
bool exprCheck(Token token);
bool variableIsNumber(int type) { return type >= 0 && type <= 12; }
typedef struct AST_Node AST_Node;
struct AST_Node {
	TokenType type;
	char* token;
	struct AST_Node* lNode;
	struct AST_Node* rNode;
};
typedef AST_Node* AST_Tree;

AST_Tree parseTree(Tokens tokens) {
	AST_Tree tree = calloc(MAX_TOKENS, sizeof(AST_Node));

	return tree;
}

strng parse(Tokens tokens) {
	strng cGeneratedCode = "\t/*\n\t * Code generated by the FLTC - Float Code Compiler;\n\t * More information at https://github.com/texugo-lab/fltc\n\t */\n";

	for (int i = 0; i <= MAX_TOKENS; ++i) {
		if (!tokens[i].token || !tokens[i].type) break;

		if (tokens[i].type == NEWLINE) continue;
		if (tokens[i].type == KEYWORD && getKeyword(tokens[i].token) == 0) {
			if (exprCheck(tokens[i + 1]) && tokens[i + 2].type == NEWLINE) {
				if (tokens[i + 1].type == NUMBER) {
					cGeneratedCode = textFormat("%s\t%s %s;\n", cGeneratedCode, keywordsRep[getKeyword(tokens[i].token)], tokens[i + 1].token);
				} else if (tokens[i + 1].type == IDENTIFIER) {
					if (variableExists(tokens[i + 1].token) == -1) {
						printf("Variable not defined: %s\n", tokens[i + 1].token);
						exit(EXIT_FAILURE);
					}
					cGeneratedCode = textFormat("%s\t%s %s;\n", cGeneratedCode, keywordsRep[getKeyword(tokens[i].token)], tokens[i + 1].token);
				}
				i += 3;
			}
			continue;
		}
		if (tokens[i].type == VARIABLE && tokens[i + 1].type == IDENTIFIER && tokens[i + 2].type == ASSIGNMENT && tokens[i + 4].type == NEWLINE) {
			int keyword = getVariableKeyword(tokens[i].token);
			if (keyword != -1 && exprCheck(tokens[i + 3])) {
				cGeneratedCode = textFormat("%s\t%s %s = %s;\n", cGeneratedCode, variablesRep[keyword], tokens[i + 1].token, tokens[i + 3].token);
				variableAppend(tokens[i + 1].token, keyword);
				i += 5;
			}
			continue;
		}
		printf("Invalid Expression\n");
		exit(1);
	}
	return cGeneratedCode;
}

void variableAppend(strng identifier, int type) {
	for (int i = 0; i < MAX_VARIABLES; ++i) {
		if (!variableTables[type][i]) {
			variableTables[type][i] = strdup(identifier);
			break;
		}
	}
}

int variableExists(strng identifier) {
	for (size_t i = 0; i < VARIABLE_COUNT; ++i) {
		for (int j = 0; j < MAX_VARIABLES; ++i) {
			if (!variableTables[i][j]) break;
			if (strcmp(variableTables[i][j], identifier) == 0) return i;
		}
	}
	return -1;
}

int getVariableKeyword(strng keyword) {
	for (size_t i = 0; i < VARIABLE_COUNT; ++i) {
		if (strcmp(keyword, variables[i]) == 0) {
			return i;
		}
	}
	return -1;
}

int getKeyword(strng keyword) {
	for (size_t i = 0; i < VARIABLE_COUNT; ++i) {
		if (strcmp(keyword, keywords[i]) == 0) {
			return i;
		}
	}
	return -1;
}

bool exprCheck(Token token) {
	return token.type == NUMBER || token.type == IDENTIFIER;
}
